import { useState } from "react";
import { IPOCandidate } from "../types";
import DashboardChart from "./DashboardChart";
import {
  ChevronDown,
  ChevronUp,
  Lock,
  Zap,
  TrendingUp,
  Calendar,
  Users,
  Award,
  ShieldAlert,
  Calculator,
  Percent,
  Sliders,
  DollarSign
} from "lucide-react";

interface CandidatesTableProps {
  candidates: IPOCandidate[];
  currentTier: string;
  onSelectCandidateForAnalysis: (name: string) => void;
}

export default function CandidatesTable({
  candidates,
  currentTier,
  onSelectCandidateForAnalysis,
}: CandidatesTableProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <section className="px-6 md:px-12 max-w-7xl mx-auto py-12" id="candidates">
      <div className="mb-8 flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <h2 className="text-3xl md:text-4xl font-black font-serif italic text-white tracking-tight">
            Live IPO Intelligence Pipeline
          </h2>
          <p className="text-[#94a3b8] mt-2 font-light">
            Real-time algorithmic predictions generated by signal convergence, liquidity triggers, and regulatory S-1 milestones.
          </p>
        </div>
        <div className="flex items-center gap-2 text-[10px] font-bold font-mono bg-[#06b6d4]/10 border border-[#06b6d4]/30 px-3.5 py-2 rounded-full text-[#06b6d4] tracking-wider">
          <span className="w-1.5 h-1.5 rounded-full bg-[#06b6d4] animate-pulse" />
          <span>LIVE PIPELINE ACTIVE</span>
        </div>
      </div>

      <div className="bg-[#020617]/90 border border-white/10 rounded-2xl overflow-hidden shadow-2xl">
        {/* Table Header */}
        <div className="hidden lg:grid grid-cols-12 gap-4 px-6 py-4 bg-[#0f172a]/40 border-b border-white/10 text-[10px] font-mono font-black uppercase text-[#64748b] tracking-[0.2em]">
          <div className="col-span-3">Company Name</div>
          <div className="col-span-3">IPO Probability Estimate</div>
          <div className="col-span-2">Valuation (Est.)</div>
          <div className="col-span-1 text-center">Confidence</div>
          <div className="col-span-1.5 text-center">Investment Score</div>
          <div className="col-span-1.5 text-right">Optimal Window</div>
        </div>

        {/* Candidate List */}
        <div className="divide-y divide-white/10">
          {candidates.map((c) => (
            <CandidateRow
              key={c.id}
              c={c}
              currentTier={currentTier}
              isExpanded={expandedId === c.id}
              onToggle={() => toggleExpand(c.id)}
              onSelectCandidateForAnalysis={onSelectCandidateForAnalysis}
            />
          ))}
        </div>

        {/* Elegant Quote Block at the bottom of the Table */}
        <div className="p-8 border-t border-white/10 text-center italic text-[#64748b] font-serif text-lg">
          "The smartest money is already looking for the exit sign."
        </div>
      </div>
    </section>
  );
}

interface CandidateRowProps {
  key?: string;
  c: IPOCandidate;
  currentTier: string;
  isExpanded: boolean;
  onToggle: () => void;
  onSelectCandidateForAnalysis: (name: string) => void;
}

function CandidateRow({
  c,
  currentTier,
  isExpanded,
  onToggle,
  onSelectCandidateForAnalysis,
}: CandidateRowProps) {
  const [activeSubTab, setActiveSubTab] = useState<"profile" | "modeler">("profile");

  // Valuation Sandbox State
  const [revenueGrowth, setRevenueGrowth] = useState(60); // 60% growth
  const [exitMultiple, setExitMultiple] = useState(15); // 15x multiple
  const [dilution, setDilution] = useState(15); // 15% dilution

  const isTierLocked = () => currentTier === "free";

  const getScoreColor = (score: number) => {
    if (score >= 70) return "text-emerald-400 bg-emerald-500/10 border-emerald-500/20";
    if (score >= 40) return "text-cyan-400 bg-cyan-500/10 border-cyan-500/20";
    return "text-purple-400 bg-purple-500/10 border-purple-500/20";
  };

  const getTimingColor = (timing: string) => {
    switch (timing) {
      case "immediate":
        return "text-emerald-400 bg-emerald-500/10 border-emerald-500/20";
      case "near":
        return "text-[#06b6d4] bg-[#06b6d4]/10 border-[#06b6d4]/20";
      case "medium":
        return "text-purple-400 bg-purple-500/10 border-purple-500/20";
      default:
        return "text-[#64748b] bg-slate-900 border-white/5";
    }
  };

  const getLogoStyle = (char: string) => {
    switch (char) {
      case "A":
        return "bg-white text-black";
      case "O":
        return "bg-[#8b5cf6] text-white";
      case "D":
        return "bg-slate-900 border border-white/20 text-white";
      default:
        return "bg-[#0f172a] border border-white/10 text-slate-300";
    }
  };

  // exit calculation variables
  const currentValuationAvg = (c.valuationLow + c.valuationHigh) / 2;
  const projectedARR = c.revenue * (1 + revenueGrowth / 100);
  const projectedExitValuation = projectedARR * exitMultiple;
  const returnMultiple = projectedExitValuation / currentValuationAvg;
  const returnOn1M = 1 * returnMultiple * (1 - dilution / 100);

  return (
    <div className="transition-all duration-300">
      {/* Main Row */}
      <div
        onClick={onToggle}
        className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-center px-6 py-5 hover:bg-[#0f172a]/20 cursor-pointer transition-colors"
      >
        {/* Name and Ticker */}
        <div className="col-span-3 flex items-center gap-4">
          {c.logoUrl ? (
            <img src={c.logoUrl} alt={c.name} className="w-10 h-10 rounded-lg object-cover border border-white/10 shadow-md" />
          ) : (
            <div className={`w-10 h-10 rounded-lg flex items-center justify-center font-serif font-black text-sm shadow-md ${getLogoStyle(c.logoChar)}`}>
              {c.logoChar}
            </div>
          )}
          <div>
            <div className="font-bold text-white text-base tracking-tight">{c.name}</div>
            <div className="text-[10px] font-mono text-[#64748b]">
              {c.ticker} · {c.sector}
            </div>
          </div>
        </div>

        {/* Probability Bar */}
        <div className="col-span-3 flex flex-col justify-center">
          <div className="flex items-center justify-between text-[11px] font-mono font-semibold mb-1 text-[#94a3b8]">
            <span>Probability</span>
            <span className="text-emerald-400 font-bold">{(c.ipoProbability * 100).toFixed(1)}%</span>
          </div>
          <div className="w-full h-[2px] bg-white/5 overflow-hidden rounded-full">
            <div
              className="h-full bg-emerald-400 rounded-full transition-all duration-1000"
              style={{ width: `${c.ipoProbability * 100}%` }}
            />
          </div>
        </div>

        {/* Valuation Range */}
        <div className="col-span-2 flex flex-col lg:items-start justify-center">
          <span className="lg:hidden text-[10px] font-mono text-[#64748b] uppercase tracking-widest mb-1">Valuation</span>
          <span className="font-mono text-sm text-white font-bold">
            ${c.valuationLow}B - ${c.valuationHigh}B
          </span>
        </div>

        {/* Confidence */}
        <div className="col-span-1 flex flex-col lg:items-center justify-center">
          <span className="lg:hidden text-[10px] font-mono text-[#64748b] uppercase tracking-widest mb-1">Confidence</span>
          <span className="font-mono text-sm text-[#94a3b8] font-semibold">
            {(c.confidence * 100).toFixed(0)}%
          </span>
        </div>

        {/* Investment Score */}
        <div className="col-span-1.5 flex flex-col lg:items-center justify-center">
          <span className="lg:hidden text-[10px] font-mono text-[#64748b] uppercase tracking-widest mb-1">Investment Score</span>
          {isTierLocked() ? (
            <div className="inline-flex items-center gap-1 px-2.5 py-1 rounded bg-[#0f172a] border border-white/10 text-slate-500 text-[10px] font-bold select-none">
              <Lock className="w-3 h-3" />
              <span>PRO</span>
            </div>
          ) : (
            <span className={`px-2.5 py-1 rounded border text-xs font-black font-mono ${getScoreColor(c.score)}`}>
              {c.score}/100
            </span>
          )}
        </div>

        {/* Optimal Timing / Expand Trigger */}
        <div className="col-span-1.5 flex items-center justify-between lg:justify-end gap-3">
          <div className="flex flex-col lg:items-end">
            <span className="lg:hidden text-[10px] font-mono text-[#64748b] uppercase tracking-widest mb-1">Optimal Window</span>
            <span className={`px-2.5 py-1 rounded text-[10px] font-bold uppercase tracking-wider ${getTimingColor(c.timing)}`}>
              {c.timingLabel}
            </span>
          </div>
          <div>
            {isExpanded ? (
              <ChevronUp className="w-4 h-4 text-slate-500" />
            ) : (
              <ChevronDown className="w-4 h-4 text-slate-500" />
            )}
          </div>
        </div>
      </div>

      {/* Expanded Section */}
      {isExpanded && (
        <div className="px-6 py-8 bg-[#0f172a]/30 border-t border-white/10 grid grid-cols-1 md:grid-cols-12 gap-8 text-slate-300">
          <div className="md:col-span-7 flex flex-col gap-6">
            <div>
              <h4 className="text-[10px] font-mono tracking-[0.2em] uppercase text-[#64748b] mb-2">Company Overview</h4>
              <p className="text-[#94a3b8] text-sm leading-relaxed font-light">{c.description}</p>
            </div>

            {/* Interactive Telemetry Chart */}
            {c.history && (
              <div>
                <DashboardChart candidateName={c.name} ticker={c.ticker} history={c.history} />
              </div>
            )}

            {/* Sub-Tabs Selector */}
            <div className="flex border-b border-white/5 pb-1 gap-4">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setActiveSubTab("profile");
                }}
                className={`pb-2 text-[10px] font-mono font-black uppercase tracking-wider transition-all border-b-2 ${
                  activeSubTab === "profile" ? "border-[#06b6d4] text-white" : "border-transparent text-slate-500 hover:text-slate-300"
                }`}
              >
                Operational Profile
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setActiveSubTab("modeler");
                }}
                className={`pb-2 text-[10px] font-mono font-black uppercase tracking-wider transition-all border-b-2 flex items-center gap-1.5 ${
                  activeSubTab === "modeler" ? "border-purple-500 text-white" : "border-transparent text-slate-500 hover:text-slate-300"
                }`}
              >
                <Calculator className="w-3.5 h-3.5" />
                Valuation exit modeler
              </button>
            </div>

            {/* Sub-tab 1: Profile View */}
            {activeSubTab === "profile" && (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 bg-[#0f172a] border border-white/5 rounded-xl">
                  <div className="flex items-center gap-2 text-[10px] font-mono text-[#64748b] uppercase mb-2">
                    <Users className="w-3.5 h-3.5 text-[#06b6d4]" />
                    <span>Key Executives</span>
                  </div>
                  <div className="flex flex-col gap-2 pt-1">
                    {c.executiveProfiles && c.executiveProfiles.length > 0 ? (
                      c.executiveProfiles.map((exec, index) => (
                        <div key={index} className="flex items-center gap-3 bg-[#020617]/70 p-2 rounded-lg border border-white/5">
                          <img
                            src={exec.avatarUrl}
                            alt={exec.name}
                            className="w-8 h-8 rounded-full object-cover border border-[#06b6d4]/40"
                          />
                          <div>
                            <div className="text-xs font-bold text-white tracking-tight">{exec.name}</div>
                            <div className="text-[10px] text-[#06b6d4] font-mono">{exec.role}</div>
                          </div>
                        </div>
                      ))
                    ) : (
                      c.keyExecutives.map((exec, index) => (
                        <div key={index} className="flex items-center gap-2.5 bg-[#020617]/70 p-2 rounded-lg border border-white/5">
                          <div className="w-7 h-7 rounded-full bg-[#06b6d4]/20 text-[#06b6d4] flex items-center justify-center text-xs font-bold font-mono">
                            {exec.charAt(0)}
                          </div>
                          <span className="text-xs font-bold text-white">{exec}</span>
                        </div>
                      ))
                    )}
                  </div>
                </div>
                <div className="p-4 bg-[#0f172a] border border-white/5 rounded-xl">
                  <div className="flex items-center gap-2 text-[10px] font-mono text-[#64748b] uppercase mb-2">
                    <Award className="w-3.5 h-3.5 text-[#8b5cf6]" />
                    <span>Competitive Position</span>
                  </div>
                  <p className="text-sm text-[#94a3b8] leading-normal font-light">{c.competitivePosition}</p>
                </div>
              </div>
            )}

            {/* Sub-tab 2: Valuation Modeler View */}
            {activeSubTab === "modeler" && (
              <div className="relative p-5 bg-[#0f172a]/60 border border-white/5 rounded-xl space-y-4 overflow-hidden">
                {isTierLocked() ? (
                  <div className="absolute inset-0 bg-black/80 backdrop-blur-sm z-10 flex flex-col items-center justify-center text-center p-6 space-y-3">
                    <Lock className="w-8 h-8 text-purple-400" />
                    <div>
                      <h5 className="text-sm font-bold text-white">Valuation Exit Simulator Locked</h5>
                      <p className="text-[11px] text-[#94a3b8] mt-1 max-w-[280px] leading-relaxed mx-auto">
                        Upgrade your account to Creator or above to model compound ARR growth and exit multiples.
                      </p>
                    </div>
                  </div>
                ) : null}

                <div className="flex items-center gap-2 pb-2 border-b border-white/5">
                  <Calculator className="w-4 h-4 text-purple-400" />
                  <span className="text-xs font-mono font-bold text-white uppercase tracking-wider">ROI Underwriting Sandbox</span>
                </div>

                {/* Input Parameters */}
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  <div className="space-y-1.5">
                    <label className="text-[10px] font-mono text-[#64748b] uppercase font-bold flex justify-between">
                      <span>ARR Growth Rate</span>
                      <span className="text-purple-400">{revenueGrowth}%</span>
                    </label>
                    <input
                      type="range"
                      min="10"
                      max="200"
                      step="5"
                      value={revenueGrowth}
                      onChange={(e) => setRevenueGrowth(Number(e.target.value))}
                      className="w-full h-1 bg-white/5 rounded-lg appearance-none cursor-pointer accent-purple-500"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-[10px] font-mono text-[#64748b] uppercase font-bold flex justify-between">
                      <span>Exit Revenue Multiple</span>
                      <span className="text-purple-400">{exitMultiple}x</span>
                    </label>
                    <input
                      type="range"
                      min="5"
                      max="45"
                      step="1"
                      value={exitMultiple}
                      onChange={(e) => setExitMultiple(Number(e.target.value))}
                      className="w-full h-1 bg-white/5 rounded-lg appearance-none cursor-pointer accent-purple-500"
                    />
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-[10px] font-mono text-[#64748b] uppercase font-bold flex justify-between">
                      <span>Post-IPO Dilution</span>
                      <span className="text-purple-400">{dilution}%</span>
                    </label>
                    <input
                      type="range"
                      min="5"
                      max="40"
                      step="1"
                      value={dilution}
                      onChange={(e) => setDilution(Number(e.target.value))}
                      className="w-full h-1 bg-white/5 rounded-lg appearance-none cursor-pointer accent-purple-500"
                    />
                  </div>
                </div>

                {/* Calculated Results */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-[#020617] p-3.5 rounded-lg border border-white/5 text-center mt-2">
                  <div>
                    <span className="text-[8px] font-mono text-slate-500 block uppercase font-bold">Projected ARR</span>
                    <span className="text-xs font-mono text-white font-bold">${projectedARR.toFixed(2)}B</span>
                  </div>
                  <div>
                    <span className="text-[8px] font-mono text-slate-500 block uppercase font-bold">Projected Exit Value</span>
                    <span className="text-xs font-mono text-white font-bold">${projectedExitValuation.toFixed(1)}B</span>
                  </div>
                  <div>
                    <span className="text-[8px] font-mono text-slate-500 block uppercase font-bold">ROI Multiplier (MOIC)</span>
                    <span className="text-xs font-mono text-emerald-400 font-black">{returnMultiple.toFixed(2)}x</span>
                  </div>
                  <div>
                    <span className="text-[8px] font-mono text-slate-500 block uppercase font-bold">Payout on $1M</span>
                    <span className="text-xs font-mono text-[#06b6d4] font-black">${returnOn1M.toFixed(2)}M</span>
                  </div>
                </div>
              </div>
            )}

            <div className="flex flex-wrap items-center gap-6 pt-2">
              <div className="text-sm">
                <span className="text-[#64748b] font-mono text-[10px] uppercase tracking-wider">Annualized Revenue Run-Rate: </span>
                <strong className="text-white font-mono font-bold">${c.revenue}B</strong>
              </div>
              <div className="text-sm">
                <span className="text-[#64748b] font-mono text-[10px] uppercase tracking-wider">Funding Stage: </span>
                <strong className="text-white font-mono font-bold">{c.fundingStage}</strong>
              </div>
            </div>

            <div className="pt-2">
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectCandidateForAnalysis(c.name);
                }}
                className="px-5 py-3 bg-white text-black hover:bg-slate-200 text-xs font-black uppercase tracking-widest transition-all duration-300 flex items-center gap-2 shadow-lg shadow-white/5"
              >
                <Zap className="w-3.5 h-3.5 fill-black" />
                Generate OMNIBRAIN Narrative Report
              </button>
            </div>
          </div>

          <div className="md:col-span-5 flex flex-col">
            <h4 className="text-[10px] font-mono tracking-[0.2em] uppercase text-[#64748b] mb-4 flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-[#06b6d4]" />
              <span>IPO Convergence Signals Timeline</span>
            </h4>

            <div className="relative border-l border-white/10 pl-4 ml-2 space-y-5">
              {c.signals.map((sig, index) => (
                <div key={index} className="relative group/sig">
                  {/* Marker */}
                  <div className="absolute -left-[21px] top-1 w-2.5 h-2.5 rounded-full bg-[#06b6d4] border border-[#020617] group-hover/sig:scale-125 transition-transform" />
                  
                  <div className="flex items-center justify-between text-[11px] text-[#64748b] font-mono mb-1">
                    <span className="flex items-center gap-1 text-[#06b6d4] font-semibold">
                      <Calendar className="w-3 h-3" />
                      {sig.date}
                    </span>
                    <span className="bg-[#0f172a] border border-white/5 px-2 py-0.5 rounded text-white font-bold text-[9px] uppercase tracking-wider">
                      Weight: {sig.weight}
                    </span>
                  </div>
                  <p className="text-sm font-semibold text-white leading-snug">{sig.desc}</p>
                </div>
              ))}
            </div>

            {isTierLocked() && (
              <div className="mt-6 p-4 bg-[#8b5cf6]/5 border border-[#8b5cf6]/20 rounded-xl flex items-start gap-3">
                <ShieldAlert className="w-5 h-5 text-[#8b5cf6] shrink-0 mt-0.5" />
                <div>
                  <p className="text-xs font-bold text-slate-200">Pre-IPO Trading Access Locked</p>
                  <p className="text-xs text-[#94a3b8] mt-1">
                    Upgrade to the Predictor or Trader tier to unlock full quantitative rating algorithms, investment scoring arrays, and pre-IPO secondary market exchange routing.
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
